services:
  # Python Backend Service
  backend:
    build: ./backend
    container_name: earthquake_backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    restart: always

  # React Frontend Service
  frontend:
    build: ./frontend
    container_name: earthquake_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  model_data: